spring:
  datasource:
    url: jdbc:mysql://localhost:3307/familykartdb
    username: root
    password: root		

#jpa specific properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false  # ← correct producer property

topicName: order-events
reduceStockTopicName: reduce-stock-events  
notificationTopicNameForPaymentSuccess: notification-events-success
message: this is order service profile